[package]
name = "audiens"
version = "0.0.1"
authors = ["Rasmus Kildevæld"]
edition = "2021"


[lib]
proc-macro = true

[dependencies]
syn = { version = "2" }
quote = "1"
proc-macro2 = "1"
darling = "0.20"
